rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
before_script: rake test
script: gem build pazaak.gemspec
deploy:
  on:
    tags: true
