rvm:
  #- 1.8.6
  #- 1.8.7
  #- 1.9.1
  #- 1.9.2
  #- 1.9.3
  #- 2.0.0
  #- 2.1
  #- 2.2
  - 2.3
  - 2.4
  - 2.5
  - $API_KEY
  #- ruby-head
before_script: rake test
script: gem build pazaak.gemspec
deploy:
  provider: rubygems
  on:
    tags: true
